/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutImport } from './routes/_public-layout'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as PublicLayoutSignUpImport } from './routes/_public-layout/sign-up'
import { Route as PublicLayoutLoginImport } from './routes/_public-layout/login'
import { Route as LayoutWorkspaceSlugStudentsIndexImport } from './routes/_layout/$workspace-slug/students/index'
import { Route as LayoutWorkspaceSlugStudentsIdImport } from './routes/_layout/$workspace-slug/students/$id'

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_public-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const PublicLayoutSignUpRoute = PublicLayoutSignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicLayoutLoginRoute = PublicLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const LayoutWorkspaceSlugStudentsIndexRoute =
  LayoutWorkspaceSlugStudentsIndexImport.update({
    path: '/$workspace-slug/students/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutWorkspaceSlugStudentsIdRoute =
  LayoutWorkspaceSlugStudentsIdImport.update({
    path: '/$workspace-slug/students/$id',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public-layout': {
      id: '/_public-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public-layout/login': {
      id: '/_public-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_public-layout/sign-up': {
      id: '/_public-layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicLayoutSignUpImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_layout/$workspace-slug/students/$id': {
      id: '/_layout/$workspace-slug/students/$id'
      path: '/$workspace-slug/students/$id'
      fullPath: '/$workspace-slug/students/$id'
      preLoaderRoute: typeof LayoutWorkspaceSlugStudentsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$workspace-slug/students/': {
      id: '/_layout/$workspace-slug/students/'
      path: '/$workspace-slug/students'
      fullPath: '/$workspace-slug/students'
      preLoaderRoute: typeof LayoutWorkspaceSlugStudentsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutWorkspaceSlugStudentsIdRoute,
    LayoutWorkspaceSlugStudentsIndexRoute,
  }),
  PublicLayoutRoute: PublicLayoutRoute.addChildren({
    PublicLayoutLoginRoute,
    PublicLayoutSignUpRoute,
  }),
})

/* prettier-ignore-end */
